name: CI

on:
  push:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - name: Set up Pixi environment
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.18.0
        cache: true
        manifest-path: pyproject.toml
    - name: Run tests
      run: |
        pixi run -e dev test