# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.8
      with:
        environments: dev
        activate-environment: true
    - run: which python | grep '.pixi/envs/py311/bin/python'
    - run: |
        test
